package me.risky.domain;

public class Download {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download.Id
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column download.remark
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download.Id
     *
     * @return the value of download.Id
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download.Id
     *
     * @param id the value for download.Id
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column download.remark
     *
     * @return the value of download.remark
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column download.remark
     *
     * @param remark the value for download.remark
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}