package me.risky.domain;

import java.util.Date;

public class Version {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.Id
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.name
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.code
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.date
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.remark
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.url
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.Id
     *
     * @return the value of version.Id
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.Id
     *
     * @param id the value for version.Id
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.name
     *
     * @return the value of version.name
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.name
     *
     * @param name the value for version.name
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.code
     *
     * @return the value of version.code
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.code
     *
     * @param code the value for version.code
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.date
     *
     * @return the value of version.date
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.date
     *
     * @param date the value for version.date
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.remark
     *
     * @return the value of version.remark
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.remark
     *
     * @param remark the value for version.remark
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.url
     *
     * @return the value of version.url
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.url
     *
     * @param url the value for version.url
     *
     * @mbggenerated Mon Feb 24 09:12:16 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }
}