package com.nupt.orm;


import com.nupt.domain.Attach;
import com.nupt.domain.AttachExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACH
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    int countByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACH
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    int deleteByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACH
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    int insert(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACH
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    int insertSelective(Attach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACH
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    List<Attach> selectByExample(AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACH
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    int updateByExampleSelective(@Param("record") Attach record, @Param("example") AttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ATTACH
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    int updateByExample(@Param("record") Attach record, @Param("example") AttachExample example);



    //手工添加

    void deleteAttach(String type);
}