package com.nupt.domain;

public class Attach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACH.ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACH.NAME
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACH.TYPE
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACH.CONTENT
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACH.PROJECT_ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACH.CREATE_TIME
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTACH.USER_ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACH.ID
     *
     * @return the value of ATTACH.ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACH.ID
     *
     * @param id the value for ATTACH.ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACH.NAME
     *
     * @return the value of ATTACH.NAME
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACH.NAME
     *
     * @param name the value for ATTACH.NAME
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACH.TYPE
     *
     * @return the value of ATTACH.TYPE
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACH.TYPE
     *
     * @param type the value for ATTACH.TYPE
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACH.CONTENT
     *
     * @return the value of ATTACH.CONTENT
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACH.CONTENT
     *
     * @param content the value for ATTACH.CONTENT
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACH.PROJECT_ID
     *
     * @return the value of ATTACH.PROJECT_ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACH.PROJECT_ID
     *
     * @param projectId the value for ATTACH.PROJECT_ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACH.CREATE_TIME
     *
     * @return the value of ATTACH.CREATE_TIME
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACH.CREATE_TIME
     *
     * @param createTime the value for ATTACH.CREATE_TIME
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTACH.USER_ID
     *
     * @return the value of ATTACH.USER_ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTACH.USER_ID
     *
     * @param userId the value for ATTACH.USER_ID
     *
     * @mbggenerated Thu Nov 07 22:16:27 CST 2013
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}