package com.nupt.domain;

import java.util.Date;

public class Location {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.Id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.Longitude
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.Latitude
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.has_check
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private Integer hasCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.phone_id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private Integer phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.equipment_id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private Integer equipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.create_time
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.address
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.Id
     *
     * @return the value of location.Id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.Id
     *
     * @param id the value for location.Id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.Longitude
     *
     * @return the value of location.Longitude
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.Longitude
     *
     * @param longitude the value for location.Longitude
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.Latitude
     *
     * @return the value of location.Latitude
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.Latitude
     *
     * @param latitude the value for location.Latitude
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.has_check
     *
     * @return the value of location.has_check
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public Integer getHasCheck() {
        return hasCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.has_check
     *
     * @param hasCheck the value for location.has_check
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setHasCheck(Integer hasCheck) {
        this.hasCheck = hasCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.phone_id
     *
     * @return the value of location.phone_id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.phone_id
     *
     * @param phoneId the value for location.phone_id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.equipment_id
     *
     * @return the value of location.equipment_id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public Integer getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.equipment_id
     *
     * @param equipmentId the value for location.equipment_id
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setEquipmentId(Integer equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.create_time
     *
     * @return the value of location.create_time
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.create_time
     *
     * @param createTime the value for location.create_time
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.address
     *
     * @return the value of location.address
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.address
     *
     * @param address the value for location.address
     *
     * @mbggenerated Sat Dec 14 19:53:58 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }
}