package me.risky.orm;

import java.util.List;
import me.risky.domain.Download;
import me.risky.domain.DownloadExample;
import org.apache.ibatis.annotations.Param;

public interface DownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int countByExample(DownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int deleteByExample(DownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int insert(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int insertSelective(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    List<Download> selectByExample(DownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    Download selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int updateByExampleSelective(@Param("record") Download record, @Param("example") DownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int updateByExample(@Param("record") Download record, @Param("example") DownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int updateByPrimaryKeySelective(Download record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table download
     *
     * @mbggenerated Fri Feb 21 16:06:41 CST 2014
     */
    int updateByPrimaryKey(Download record);
}